#define WC_SKIP_GLOBALS
#include "graphics_backend.h"
// Forward-declare seulement les types pour eviter double implementation dr_flac/stb_vorbis
namespace audiere {
    struct WCAudioDevice;
    struct WCAudioPlayer;
    typedef WCAudioDevice *AudioDevicePtr;
    typedef WCAudioPlayer *OutputStreamPtr;
}
using namespace audiere;
#include "audio.h"

////SOUND/////////////////////////////////////////////////////////////////////
AudioDevicePtr device;
OutputStreamPtr player1;
OutputStreamPtr player2;
OutputStreamPtr player3;
OutputStreamPtr player4;
char audio_device_name[256];
char list_audio_device[16][256];
bool index_show_audio_window = 0;
int index_nbre_players_visibles = 2;
bool index_over_audio = 0;
bool index_click_move_audio_window = 0;
int XAudio = 20;
int YAudio = 20;
char list_audio_files[128][72];
int line_audio = 0;
int audiofile_selected = 0;
char audiofile_name[72];
char rep_audio[256];
char audio_folder[64] = {"demo"};
char list_audio_folders[64][64];
int nbre_audio_folders = 0;
int audio_folder_list_scroll = 0;
bool audio_folder_scroll_dragging = 0;
int audio_folder_scroll_drag_start_y = 0;
int audio_folder_scroll_drag_start_scroll = 0;
bool audio_filelist_scroll_dragging = 0;
int audio_filelist_scroll_drag_start_y = 0;
int audio_filelist_scroll_drag_start_scroll = 0;
int last_scroll_mouse_for_audio = 0;
bool audio_seekbar_dragging[4] = {0, 0, 0, 0};
volatile int mouse_double_click = 0;
bool audio_pan_dragging[4] = {0, 0, 0, 0};
bool audio_pitch_dragging[4] = {0, 0, 0, 0};
bool index_show_audio_folder_list = 0;
char temp_audio_folder[25];
char sound_files[4][72];
char soundfile_temp_loader[256 + 72];
int index_preloaded_sounds = 1;
int audio_ram_limit_mb = 300;
int length_of_file_in_player[4];
int position_of_file_in_player[4];
int player_loop_out_position[4];
int player_seek_position[4];
bool audio_do_load_midi_prev_file[4];
bool audio_do_load_midi_next_file[4];
int audiofile_cue_in_out_pos[128][4][2]; // [file][player][cue_in, cue_out]
int audio_number_total_in_folder = 0;
bool player_ignited[4];
bool player_is_playing[4];
bool player_is_onloopCue[4];
bool player_is_onloop[4];
int player_pitch[4];
float show_pitch_value[4];
int player_pan[4];
float show_pan_value[4];
int player_niveauson[4];
float show_player_niveauson[4];
int sample_rate[4];
int sample_nbr_ch[4];
bool index_edit_audio = 0;
int audio_rate[4];
bool index_loading_a_sound_file = 0;
bool midi_show_flash_seektouch[4];
bool midi_show_flash_backwardtouch[4];
bool midi_show_flash_forwardtouch[4];
bool midi_show_flash_cueIntouch[4];
bool midi_show_flash_cueOuttouch[4];
bool midi_show_flash_cueSeektouch[4];
char audiofile_name_was[4][72];
int audio_position_was[4];
int audio_volume_was[4];
int audio_pan_was[4];
int audio_pitch_was[4];
int audio_cue_in_was[4];
int audio_cue_out_was[4];
bool player_was_playing[4];
bool player_was_onloopCue[4];
bool player_was_onloop[4];
bool index_affect_audio_to_dock = 0;
int player_to_affect_to_dock = 999;
int audio_type_for_dock_affectation_is = 999;
bool index_do_audio_to_dock = 0;
int DockHasAudioVolume[48][6];
int DockHasAudioPan[48][6];
int DockHasAudioPitch[48][6];
int Player_is_piloted_by_fader[4][4];
char time_is_for_fileCueIn[4][64];
char time_is_for_fileCueOut[4][64];
char time_is_for_filePos[4][64];
char time_is_for_fileTotal[4][64];
char string_niveauson[4][16];
char string_pitch[4][12];
char string_pan[4][12];
char string_fader_stop_pos[48][4];
bool audio_autoload[4];
bool audio_autopause[4];
int player_has_file_coming_from_pos[4];
int player_position_on_save[4];
