#include "chasers.h"

//////////////////////////CHASERS//////////////////////////////////////////////
bool index_window_chasers = 0;
int index_affichage_digit_time_unit = 0;
int Xchasers = 100;
int Ychasers = 300;
bool index_over_chasers = 0;
bool index_click_move_chasers = 0;
int chaser_selected = 0;
bool index_enable_edit_chaser = 0;
bool index_affect_chaser_to_dock = 0;
bool index_do_affect_fx = 0;
int nbre_track_visualisables = 4;
int nbre_de_cases_par_track = 36;
int nbre_tracks_par_chaser = 24;
int chaser_operator_is = 0;
char chaser_name[128][25];
char chaser_track_name[128][24][25];
float time_unit[128];
int chaser_step_operation[128][24][36];
bool chaser_is_playing[128];
bool chaser_is_in_loop[128];
bool chaser_way[128];
bool chaser_aller_retour[128];
bool track_is_on[128][24];
int track_level[128][24];
int position_affichage_track_num[128];
int TrackTypeIs[128][24];
int TrackContains[128][24][514];
int TracksBuffer[128][24][514];
int MergerBufferChasers[128][514];
float index_progression_chaser_step[128];
float previous_index_progression_chaser_step[128];
int chaser_begin_step_is[128];
int chaser_end_step_is[128];
bool chaser_time_mode[128];
int chaser_time_position[128];
int chaser_start_time[128];
float chaser_start_of_step[128];
float chaser_end_of_step[128];
int chaser_step_is[128];
int previous_chaser_step_is[128];
int count_steps_for_fades[128][24];
int joint_begin_step[128][24];
int joint_end_step[128][24];
int joint_nbr_step[128][24];
int chaser_selected_for_record = 0;
int track_selected_for_record = 0;
int chaser_preset_selected_for_record = 0;
bool index_do_dock_track = 0;
bool index_do_clear_track = 0;
bool index_do_report_track = 0;
bool index_do_modify_track = 0;
bool index_do_clear_chaser = 0;
bool index_do_store_chaser_preset = 0;
bool index_do_clear_chaser_preset = 0;
int view_chaser_affected_to_fader[128][2];
bool index_slave_chaser_to_accelerometre[128];
float chaser_slaviness[128];
float previous_chaser_slaviness[128];
bool chaser_preset[128][4][24];
bool launchpad_chaser_mode = 0;
int chaser_midi_rows = 4;
int previous_color_on_chaser[8][8];
int chaser_step_launchpad[128];
int mem_to_load_in_chaser = 0;
bool index_do_store_mem_in_chaser = 0;
int TrackHasMem[128][24];
int over_track_show_channel[514];
bool i_m_over_a_track = 0;
