#pragma once
#include <vector>
#include "SmoothData.h"

extern std::vector<SmoothData> Fader_dampered;

int reset_numeric_entry();
int return_lowest(int data1, int data2);
int return_highest(int data1, int data2);
int constrain_data_to_dmx_range(int valeur);
int constrain_data_to_midi_range(int valeur);
int reset_temp_state_for_channel_macros_launch();
int fader_set_level(int cmptfader, int val);
int player1_do_stop();
int player2_do_stop();
int player3_do_stop();
int player4_do_stop();
bool check_channel_is_patched(int ch);
int constrain_int_data_to_this_range(int data, int min, int max);
int check_echo_bounce_done(int ech);
int prepare_bounce(int ech);
int recall_channel_state_in_an_echo(int ech);
int snap_fader_state(int echo, int f);
int snap_kill_and_bounce(int echo, int f);
int record_channel_ch_state_in_an_echo(int ech, int cha);
int record_channel_state_in_an_echo(int ech);
int clear_banger(int bg);
int recall_fader_state_echo(int f);
int clear_echo_levels(int ech);
int clear_ground_levels(int ech);
int clear_echo_preset(int ech);
int Draw_point_and_perform_level_on_area_NEW(int pr, int position_x, int position_y);
int recalculate_draw_sizes(int preset);
int draw_erase_drawing(int p);
int clear_draw_preset(int p);
int copy_banger(int source, int dest);
int reset_index_actions();
int reset_indexs_confirmation();
int do_clock_level_modification(int level);
int reset_channel_first_dimmer_list();
int generate_channel_preview_patch_list();
int check_presence_of_a_channel_in_views(int idch);
int check_wich_channel_is_in_view(int idch);
int check_presence_of_any_channel_in_A_view(int v);
int check_presence_of_A_channel_in_A_view(int v, int ch);
int detect_last_activ_channel_in_activ_view(int v);
int toggle(int index_to_toggle);
int bounce(int b);
int count_number_of_channels_in_view(int view_is);
int refresh_positions_preset_view_poignee();
int clear_selection_in(int view_is);
int build_preset_view_from_mem(int me, int view_is);
int build_preset_view_from_fader(int f, int view_is);
int reorder_channel_view_list_of_channels(int view_is);
int build_preset_view_from_all_existing_mems(int view_is);
int build_preset_view_from_all_faders(int view_is);
int build_preset_view_from_all_existing_mems_and_faders(int view_is);
int report_selection_in(int view_is);
int generate_channel_view_list_from_patched_circuits();
int record_selection_in(int view_is);
int modify_selection_in(int view_is);
int clear_plot_legend();
int reset_error_on_save_load();
int detect_error_on_save_load();
int clear_report_string();
int clear_xyrelativ_preset(int pr);
int affect_preset_xy_to_symbols(int pr);
int record_preset_xy_from_symbol(int pr);
int clear_completely_the_patch();
int show_title();
int load_plan_of_theatre(char name_of_plan[256], bool rescan_width_eight);
int set_plot_background_to_default();
int refresh_shape_factors(int shapetype);
int set_all_faders_midi_out(bool state);
int refresh_all_midi_out_faders();
int reset_window_opened_indexes();
int constrain_banger_type(int lp);
int constrain_banger_param(int lp);
int reset_banger_params(int banger_selected, int event);
int reset_banger_event(int banger_selected, int event);
int reset_audio_indexs_to_dock();
bool set_all_saves_indexes_at(bool val);
int reset_modified_levels_in_crossfade();
int exclude_reinclude_channels_from_grand_master_action();
int set_new_time_in_tap_tempo();
int refresh_hauteur_fenetre_grider();
int reset_window_positions();
int Get_channels_from_memory(int the_mem);
int search_and_desaffect_previous_midi_signal(int typaction);
int reset_index_affect_midi();
void show_type_midi(int control, const std::string command);
int attribute_midi_to_control(int faderis, int typaction, int modeaction);
int attribute_midi_solo_affectation(int faderis, int modeaction);
int process_assign_to_core(int coreis);
int detect_actual_master_lock_is();
void save_load_print_to_screen(const std::string label);
int minifader_selection_record(int mf_preset_is);
int minifader_selection_clear(int mf_preset_is);
int minifader_lockselection_record(int mf_preset_is);
int refresh_stage();
int reset_indexes_conf();
int button_midi_out_core(int xmi, int ymi, int control);
int button_midi_out_visu(int xmi, int ymi, int control);
int show_who_is_in_dock(int fader, int thedokis);
int reset_check_grada_overide_dimmers();
int reset_all_bangers();
int reset_save_load_report_string();
int scan_audio_root_folders();
int scan_audiofolder();
int snapshot_windows();
int close_all_windows();
int write_window_indexes_from_list_of_windows();
int rafraichissement_clockwheel();
int recall_windows();
int refresh_time_cursor();
int set_time_cursor_to_time_type(int the_time_wheel_datatype);
int read_time_string_entry();
int reset_midi_receiver_array();
int detect_master_lock(int mo);
int do_lock_preset(int num_preset);
int do_stock_fadersstate(bool fads, bool speeds, bool locks, bool lfos, bool loops);
int do_recall_fadersstate(bool fads, bool speeds, bool locks, bool lfos, bool loops);
int dessafect_index_curves();
int reconstruct_plot_dimmer_list_from_patch();
int patch_straight();
int patch_select_all_dimmers();
int patch_clear_selected();
int patch_to_default_selected();
int set_channel_scroll(int ch);
int set_patch_scroll(int dim);
int load_Fader_state_to_midi_array();
int send_my_midi_note(int letype, int lechannel, int lanote, int lavelocite, int laduree);
int send_my_midi_note_delayed(int letype, int lechannel, int lanote, int lavelocite, int laduree, int delay);
int send_immidiateley_my_midi_cc(int letype, int lechannel, int lanote, int lavelocite);
int midi_send_type_message(int msgmidi);
int emit_midi_out();
int load_etat_picker_dans_dockcolor(int dcolor_selected);
int refresh_ocv_settings();
int refresh_decay();
int LoadWhiteCatColorProfil();
int record_memory(int mem_is);
int refresh_mem_onstage(int mem_is);
int record_memory_plus_faders(int mem_is);
int overrecord_memory_plus_faders(int mem_is);
int snap_mem_to_copy();
int copy_mem_in(int mem_n);
int prepare_crossfade();
int detect_mem_before_one();
int detect_mem_preset();
int detect_mem_preset_previous();
int detect_next_preset();
int refresh_mem_onpreset(int mem_is);
int create_memory(int mem_to_create);
int create_memory_plus_faders(int mem_to_create);
int delete_memory(int mem_to_delete);
int refresh_integrated_gridplayer1();
int do_load_mem_preset_while_crossfade(int mem_is);
int do_double_go_function();
int do_go_back_function();
int do_go_function();
int patch_unselect_all_dimmers();
int build_default_curve(int curve);
int set_to_default_my_roi(int dkprpreset, int dkpr);
int set_to_default_my_trackers();
int set_to_default_this_tracker(int Tcker);
int write_show_coming_from();
int scan_for_free_dock();
int detect_dock_used(int numfad);
int refresh_minifader_state_view_core(int cmptfader);
int do_action_on_selected_minifaders(int action);
int match_minifaders();
int affect_time_entry_to_mem(int index_t, int mem_set_to_time);
int do_sprintf_job();
int remember_config_page();
int window_who_is_on_top();
int substract_a_window(int id);
int clear_ip_artnet();
int GlobInit();
int reset_show();
